package Cell;


/**
* Cell/Station.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* среда, 16 мая 2018 г., 0:19:17 Москва, стандартное время
*/


/* =B5@D59A 107>2>9 AB0=F88 */
public interface Station extends StationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Station
