package Cell;

/**
* Cell/StationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cell.idl
* среда, 16 мая 2018 г., 0:19:17 Москва, стандартное время
*/


/* =B5@D59A 107>2>9 AB0=F88 */
public final class StationHolder implements org.omg.CORBA.portable.Streamable
{
  public Cell.Station value = null;

  public StationHolder ()
  {
  }

  public StationHolder (Cell.Station initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Cell.StationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Cell.StationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Cell.StationHelper.type ();
  }

}
